In [6]:
import pandas as pd

In [10]:
dataset = pd.read_csv("Salary_dataset.csv")

In [11]:
dataset

   Employee_ID    Department  Years_of_Experience  Salary_USD
0       EMP001         Sales                   12      107986
1       EMP002  Data Science                    7      120853
2       EMP003     Marketing                    9       90279
3       EMP004  Data Science                    8      119663
4       EMP005  Data Science                   12      134998
..         ...           ...                  ...         ...
95      EMP096     Marketing                   11       98565
96      EMP097  Data Science                    9      128794
97      EMP098   Engineering                   14      138534
98      EMP099   Engineering                    5      105561
99      EMP100            HR                    1       54869

[100 rows x 4 columns]

In [12]:
independantVar = dataset[["Years_of_Experience"]]
independantVar

    Years_of_Experience
0                    12
1                     7
2                     9
3                     8
4                    12
..                  ...
95                   11
96                    9
97                   14
98                    5
99                    1

[100 rows x 1 columns]

In [13]:
dependantVar = dataset[["Salary_USD"]]
dependantVar

    Salary_USD
0       107986
1       120853
2        90279
3       119663
4       134998
..         ...
95       98565
96      128794
97      138534
98      105561
99       54869

[100 rows x 1 columns]

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independantVar,dependantVar,test_size=0.30,random_state=0)

In [25]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [27]:
weight = regressor.coef_
weight

array([[3433.76297799]])

In [28]:
bias = regressor.intercept_
bias

array([73243.79479057])

In [ ]:
# Evaluation Metrix

In [29]:
y_predict = regressor.predict(x_test)

In [30]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_predict)

In [31]:
r_score

0.4565666703319987

In [ ]:
#deployment  - Phase-2

In [5]:
import pickle
fileName ="finalized_model_linear.sav"

In [6]:
pickle.dump(regressor,open(fileName,'wb'))

NameError: name 'regressor' is not defined

In [ ]:
#wb means write binary , finally save the model

In [ ]:
#Load to check the model

In [2]:
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb'))
result = loaded_model.predict([[0]])

NameError: name 'pickle' is not defined

In [4]:
result

NameError: name 'result' is not defined